/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CrisisRouteImport } from './routes/crisis'
import { Route as BuddyRouteImport } from './routes/buddy'
import { Route as BalanceRouteImport } from './routes/balance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBuddyRouteImport } from './routes/api/buddy'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRoute = CrisisRouteImport.update({
  id: '/crisis',
  path: '/crisis',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyRoute = BuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceRoute = BalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuddyRoute = ApiBuddyRouteImport.update({
  id: '/api/buddy',
  path: '/api/buddy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/buddy': typeof BuddyRoute
  '/crisis': typeof CrisisRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/buddy': typeof ApiBuddyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/buddy': typeof BuddyRoute
  '/crisis': typeof CrisisRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/buddy': typeof ApiBuddyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/balance': typeof BalanceRoute
  '/buddy': typeof BuddyRoute
  '/crisis': typeof CrisisRoute
  '/help': typeof HelpRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/api/buddy': typeof ApiBuddyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/balance'
    | '/buddy'
    | '/crisis'
    | '/help'
    | '/library'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/tasks'
    | '/api/buddy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balance'
    | '/buddy'
    | '/crisis'
    | '/help'
    | '/library'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/tasks'
    | '/api/buddy'
  id:
    | '__root__'
    | '/'
    | '/balance'
    | '/buddy'
    | '/crisis'
    | '/help'
    | '/library'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/tasks'
    | '/api/buddy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BalanceRoute: typeof BalanceRoute
  BuddyRoute: typeof BuddyRoute
  CrisisRoute: typeof CrisisRoute
  HelpRoute: typeof HelpRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  ApiBuddyRoute: typeof ApiBuddyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis': {
      id: '/crisis'
      path: '/crisis'
      fullPath: '/crisis'
      preLoaderRoute: typeof CrisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy': {
      id: '/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof BuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance': {
      id: '/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof BalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buddy': {
      id: '/api/buddy'
      path: '/api/buddy'
      fullPath: '/api/buddy'
      preLoaderRoute: typeof ApiBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BalanceRoute: BalanceRoute,
  BuddyRoute: BuddyRoute,
  CrisisRoute: CrisisRoute,
  HelpRoute: HelpRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  ApiBuddyRoute: ApiBuddyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
